### ISSUE TITLE
Review CI setup

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail-ai#22]
- Update the CI tooling to use the newest and shiniest stuff from https://github.com/wagtail/cookiecutter-wagtail-package.
- Use PyPI trusted publishing to the list.
- The nightly job does not seem to execute front-end tooling.
- I don't know how the publish job could've worked if the front-end tooling had missing `src/` in the paths. See #21.
```[tasklist]
### Tasks
- [x] Update the CI tooling to use the newest and shiniest stuff from https://github.com/wagtail/cookiecutter-wagtail-package.
- [x] Use PyPI trusted publishing (#45)
- [x] Ensure front-end tooling is executed in the nightly job (#50)
```

**Comment by zerolab** [comment]
Good call!
I would add "Use PyPI trusted publishing to the list" (https://docs.pypi.org/trusted-publishers/using-a-publisher/, https://github.com/wagtail/cookiecutter-wagtail-package/blob/main/%7B%7B%20cookiecutter.__project_name_kebab%20%7D%7D/.github/workflows/publish.yml#L31-L52)

**Comment by tomusher** [comment]
The addition of the `src/` folder was recent - we haven't published a version since then. Thanks for picking up on that.

The CI setup is built on https://github.com/wagtail/cookiecutter-wagtail-package so we might be able to backport some of the recent fixes from there here, where it makes sense.

**Comment by zerolab** [comment]
This is now complete.
